/* THIS FILE IS AUTOMATICALLY GENERATED! */
// ReSharper disable All
public static class GameTag { 

    public const string Untagged = "Untagged";
    public const string Respawn = "Respawn";
    public const string Finish = "Finish";
    public const string EditorOnly = "EditorOnly";
    public const string MainCamera = "MainCamera";
    public const string Player = "Player";
    public const string GameController = "GameController";
 }

public static class GameLayer { 

    public const int Default = 0;
    public const int DefaultMask = 1 << 0;
    public const int TransparentFX = 1;
    public const int TransparentFXMask = 1 << 1;
    public const int IgnoreRaycast = 2;
    public const int IgnoreRaycastMask = 1 << 2;
    public const int Water = 4;
    public const int WaterMask = 1 << 4;
    public const int UI = 5;
    public const int UIMask = 1 << 5;
    public const int Player = 10;
    public const int PlayerMask = 1 << 10;
    public const int Enemy = 11;
    public const int EnemyMask = 1 << 11;
 }
